# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-date_create',)},
        ),
        migrations.AddField(
            model_name='answer',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
