# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ('name_category',),
            },
        ),
    ]
